sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t soobtech/docker-react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run -e CI=true soobtech/docker-react-test npm test -- --coverage

after_success:
  - docker build -t soobtech/multi-client ./client
  - docker build -t soobtech/multi-nginx ./nginx
  - docker build -t soobtech/multi-server ./server
  - docker build -t soobtech/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push soobtech/multi-client
  - docker push soobtech/multi-nginx
  - docker push soobtech/multi-server
  - docker push soobtech/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-949124841738'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
